[package]
name = "kaleidoscope"
version = "0.2.0"
license = "MIT"
authors = ["Dr. Maxim Orlovsky <orlovsky@pandoracore.com>", "Alekos Filini <@afilini>"]
description = "Command-line bitcoin and RGB wallet"
keywords = ["bitcoin", "lightning", "blockchain", "layer-2", "cryptography", "rgb"]
readme = "README.md"
edition = "2018"

[dependencies]
bitcoin-wallet = "~1.0"
bitcoin = "~0.21"
log = "~0.4"
env_logger = "~0.7"
toml = "~0.5"
serde = "~1.0"
serde_derive = "~1.0"

[dependencies.clap]
# Fix this by switching to the crate released version after 2.34+
git = "https://github.com/clap-rs/clap.git"
branch = "master"
default-features = true
